default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV["DB_USER"] || ENV["USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: url_shortener_dev

test:
  <<: *default
  database: url_shortener_test
